version: '3.7'
services:
  acl:
    container_name: acl
    build: 
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - DB_DRIVER=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=local
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes: 
      - ./:/go/src/github.com/abeatrice/acl
    networks:
      - backend
networks:
  backend:
    external: true
